# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AlamoExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamoExample
  pod 'Alamofire'

  target 'AlamoExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamoExampleUITests' do
    # Pods for testing
  end

end
